name: hello-world
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run lint
      - name: run tests
        run: npm test
  code-security:
   runs-on: ubuntu-latest
   steps:
    - name: Run Snyk to check for vulnerabilities
    - uses: actions/setup-node@v4
    - uses: actions/checkout@master
    - uses: snyk/actions/maven@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
